### ISSUE TITLE
I receive an error 'Venom wallet not found' when calling venomConnect?.checkAuth().

### ISSUE THREAD

**Issue by fox638** [web3sp/venom-connect#24]
In the file venom-connect/src/controllers/ProviderController.ts:39, set the value of the variable nTries > 0, such as 4. Alternatively, pass the value of nTries as a parameter when calling VenomConnect.getPromise() or another idea.

**Comment by makanbreid** [comment]
i cant connect my wallet to the venom sit

**Comment by rightjelkin** [comment]
Will be solved when #27 will be merged
