### ISSUE TITLE
Chrome Extension Venom Wallet Not Connecting...[Bug] 

### ISSUE THREAD

**Issue by Ajay-singh911** [web3sp/venom-connect#28]
**Describe the bug**

**Venom Connect config**
Share your venom-connect configuration in code block

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rightjelkin** [comment]
Could you please fill the issue template by your data please? You have left an empty template of issue...I can't see even your configuration and at least minimal description of problem

**Comment by lenovo1992** [comment]
some time slowly

**Comment by rightjelkin** [comment]
Please fill the issue template with your data
