### ISSUE TITLE
Wallet signature issue

### ISSUE THREAD

**Issue by Humayounshah** [web3sp/venom-connect#42]
I am working on verifying wallet signatures in our backend. Signatures signed using Android Venom wallet are not getting verified with everscale-inpage-provider on backend. The same code base works when using Chrome extension for venom wallet. Any help. Is this a known issue with Venom wallet?

here's is my code for frontend: 
 const submitWallet = async () => {
    console.log(new Address(address));
    const providerState = await venomProvider?.getProviderState?.();
    console.log(providerState?.permissions);
    const publicKey = providerState?.permissions.accountInteraction?.publicKey;
    console.log(publicKey);
    try {
      const base64 = btoa(
        JSON.stringify({
          walletAddress: address,
        }),
      );
      const sign = await venomProvider.signDataRaw({ data: base64, publicKey });
      dispatch(SubmitWallet({ publicKey, base64, signature: sign.signature }));
    } catch (errr) {
      console.log(errr);
    }
  };
  and my backend code: 
const { publicKey, base64, signature } = req.body;
  const verificaiton = await ever.verifySignature({
    publicKey,
    dataHash: base64,
    signature: signature,
  });
  if (!verificaiton.isValid) {
    return res.status(403).json({
      error: "Signature is not valid",
    });
  }

**Comment by rightjelkin** [comment]
Hello. It may be the problem of the difference between `signData `and `signDataRaw `methods. If the data was signed with `signData`, you should use the dataHash returned by the method. If it was signed with `signDataRaw`, you had better use the original data itself. take a look up [here](https://provider-docs.broxus.com/guides/cryptography.html#sign-data). This is an original documentation of inpage provider with sign-verification explanation.

**Comment by Humayounshah** [comment]
The same code base is working in the web but it's not working in the mobile wallet. do we have to add something else for the mobile wallet?

**Comment by rightjelkin** [comment]
The problem could be with `withSignatureId` parameter of `signData` method...may be mobile wallet couldn't work with it by default. Try to pass `withSignatureId: false` to `signData` method. It's OK to use `false` value for authorization purposes or signing something...signatureId is important when singing something needed to be executed on-chain (like raw SC calling) cuz it's an equivalent of network ID in ETH-like networks.
