### ISSUE TITLE
[Bug] ? I can’t connect to mainnet

### ISSUE THREAD

**Issue by AlexForbs** [web3sp/venom-connect#43]
![2](https://github.com/web3sp/venom-connect/assets/135435925/73da0aff-6e10-40c0-b997-d8d22a7df53a)

**Comment by rightjelkin** [comment]
There is a very little amount of information. I can't see even your web app config. As I can see from the screenshot, web app you are visiting is configured to use testnet only. And of course if you have chosen 'mainnet', website will ask you to switch network and it is not related with venom-connect, but with website configuration.

**Comment by rightjelkin** [comment]
If you have a problem with developing when using venom-connect, please stick to the issue template

**Comment by AlexForbs** [comment]
Принял. Спасибо
